mongoimport --db=tiqn --collection=AttDevice --file=AttDevice.json
mongoimport --db=tiqn --collection=AttLog --file=AttLog.json
mongoimport --db=tiqn --collection=AttReport --file=AttReport.json
mongoimport --db=tiqn --collection=Config --file=Config.json
mongoimport --db=tiqn --collection=Employee --file=Employee.json
mongoimport --db=tiqn --collection=HistoryGetAttLogs --file=HistoryGetAttLogs.json
mongoimport --db=tiqn --collection=HistoryGetExcelData --file=HistoryGetExcelData.json
mongoimport --db=tiqn --collection=OtRegister --file=OtRegister.json
mongoimport --db=tiqn --collection=Shift --file=Shift.json
mongoimport --db=tiqn --collection=ShiftRegister --file=ShiftRegister.json